# Configuration for Alacritty, the GPU enhanced terminal emulator.

# todo neovim, tmux, what else?

import:
  - ~/dot_files/config/alacritty/alacritty.base.yml

# Shell
#
# You can set `shell.program` to the path of your favorite shell, e.g. `/bin/fish`.
# Entries in `shell.args` are passed unmodified as arguments to the shell.
#
# Default:
#   - (macOS) /bin/bash --login
#   - (Linux) user login shell
#   - (Windows) powershell
shell:
 program: tmux
 args:
   - -u
   - -l
   # - -C
   - new-session
   - -A
   - -s
   - main
