# Configuration for Alacritty, the GPU enhanced terminal emulator.

# todo neovim, tmux, what else?

import:
  - ~/dot_files/config/alacritty/alacritty.base.yml

shell:
  program: /home/hosh/.zinit/plugins/hrkfdn---ncspot/ncspot
  args: []

window:
  title: ncspot

  class:
    instance: ncspot
    general: ncspot

