colors:
  primary:
    background: '#3d4752'
    foreground: '#e6e6e6'

  cursor:
    text: '#3d4752'
    cursor: '#b490b6'

  selection:
    text: '#3d4752'
    background: '#80bbe7'

  normal:
    black: '#77818d'
    red: '#ff8e7d'
    green: '#a3d971'
    yellow: '#ffdf67'
    blue: '#80bbe7'
    magenta: '#f6b4c8'
    cyan: '#55bba7'
    white: '#e6e6e6'

  bright:
    black: '#a5a5a5'
    red: '#FFA597'
    green: '#B5E18D'
    yellow: '#FFE585'
    blue: '#99C9EC'
    magenta: '#F8C3D3'
    cyan: '#77C9B9'
    white: '#ffffff'

  dim:
    black: '#505c6a'
    red: '#D88074'
    green: '#8FBC6B'
    yellow: '#D8C163'
    blue: '#73A4C9'
    magenta: '#D19EB0'
    cyan: '#50A496'
    white: '#cdced1'
