alias cfn-flip='docker run --rm -i --name cfn-flip -v $(pwd):/workdir -w /workdir cfn-flip'
alias cfviz='docker run --rm -i --name cfviz -v $(pwd):/workdir -w /workdir cfviz'
alias graphviz='docker run --rm -i --name graphviz -v $(pwd):/workdir -w /workdir graphviz'
alias nmap='docker run --rm -i --name nmap nmap'
alias sgviz='docker run --rm -i --name sgviz -v $HOME/.aws:/root/.aws -v $(pwd):/workdir -w /workdir sgviz'
alias sipcalc='docker run --rm -i --name sipcalc sipcalc'
alias sqlite3='docker run --rm -i --name sqlite3 -v $(pwd):/workdir -w /workdir sqlite3'
alias travis='docker run --rm -ti --name travis -v $PWD:/workdir -v $HOME/.travis:/travis travis'
alias xml='docker run --rm -i --name xml -v $(pwd):/workdir -w /workdir xml'
alias xml-format='xml fo -s 2 -R'

#alias docker-dive='podman run --rm -it wagoodman/dive:latest'
alias shit='podman run -it --rm --entrypoint /bin/sh -v ${PWD}:/workdir -w /workdir'
