[[swipe.commands]]
fingers = 3
type = "GESTURE"
up = "xdotool key ctrl+alt+Up"
down = "xdotool key ctrl+alt+Down"
left = "xdotool key alt+Right"
right = "xdotool key alt+Left"

[[swipe.commands]]
fingers = 4
type = "GESTURE"
up = "xdotool key super"
down = "xdotool key super"
# left = "xdotool key super+ctrl+alt+Right"
# right = "xdotool key super+ctrl+alt+Left"
